### ISSUE TITLE
+ news feed

### ISSUE THREAD

**Issue by bbest** [cstories-app/cstories-app.github.io#3]
- [x] searches:
   - "Humboldt" AND ("offshore wind" )
   - "Morro Bay" AND ("offshore wind" )
   - "Morro Bay" AND ("offshore wind" )

- See [News — Offshore Wind California](https://www.offshorewindca.org/news)

## `newsapi` (formerly GoogleNews API)

  * [Pricing - News API](https://newsapi.org/pricing): free 200 requests / day; 1 hr late
  * [Chapter 8 Google News API | 2021\_apis\_for\_social\_scientists\_a\_collaborative\_review.knit](https://bookdown.org/paul/apis_for_social_scientists/google-news-api.html)
  * [Get news from newsapi using R language - GeeksforGeeks](https://www.geeksforgeeks.org/get-news-from-newsapi-using-r-language/)
  * [SauravKanchan/NewsAPI: News API without any API KEY](https://github.com/SauravKanchan/NewsAPI)
  * [mkearney/newsAPI: API wrapper/R client for accessing https://newsapi.org](https://github.com/mkearney/newsAPI)

-

**Comment by bbest** [comment]
## rss handling in R

* [tidyRSS | An R package for extracting ‘tidy’ data frames from RSS, Atom, JSON and geoRSS feeds](https://robertmyles.github.io/tidyRSS/)
* [feedeR: Reading RSS and Atom Feeds from R | R-bloggers](https://www.r-bloggers.com/2016/08/feeder-reading-rss-and-atom-feeds-from-r/)
* [RSS, fantastic tool for keeping up-to-date | R-bloggers](https://www.r-bloggers.com/2022/04/rss-fantastic-tool-for-keeping-up-to-date/)

**Comment by bbest** [comment]
From @jzadra : the news package from Matt Tierney is ~6 yrs old, so prob want to go a diff't direction

**Comment by bbest** [comment]
For raw API parsing, check out:
* [Wrapping APIs • httr2](https://httr2.r-lib.org/articles/wrapping-apis.html)
* [Perform multiple requests in parallel — multi\_req\_perform • httr2](https://httr2.r-lib.org/reference/multi_req_perform.html)

**Comment by bbest** [comment]
Hi @jzadra,

Check out this little example of using the newsapi.org:

* source: [cstories-app/scripts: `news-api.qmd`](https://github.com/cstories-app/scripts/blob/main/news-api.qmd)
* rendered html: [cstories.app/scripts/news-api.html](https://cstories.app/scripts/news-api.html)

Next steps could be:

- [ ] wrapping in a little function
- [ ] performing searches specific to places, like "Humboldt", "Morro Bay" and "Santa Barbara"
- [ ] expanding searches to a month back
- [ ] organizing content in data folder with naming convention for json files
- [ ] ...

**Comment by jzadra** [comment]
Another R Package for newsapi.org: https://cran.r-project.org/web/packages/newsanchor/vignettes/usage-newsanchor.html

I have not investigated thoroughly; probably created our own API requests is more customizable.

**Comment by jzadra** [comment]
**News API**

Function features: 

- [ ] Save data pulls to keep results > 1 month old (if staying on free newsapi.org plan)
- [ ] Read search terms from simple, separate file
- [ ] Format results for news feed
- [ ] Append search terms to results table for user-filtering

Decisions to be made:
- [ ] Sort API search results by relevancy, popularity, or published date?

**Comment by bbest** [comment]
@geocoug's suggestion of each news item to have it's own *.qmd doc is a good one. The metadata can be populated into the frontmatter yaml and then a listing created per here:

https://quarto.org/docs/websites/website-listings.html

**Comment by jzadra** [comment]
Newsapi.org results are listed on the index page (currently most recent 3), and there is a News page with all results.

Next items to do:

- [ ] Add filter based on search terms
- [ ] Determine method to handle non-relevant results and/or refine search terms
- [ ] Automate running of API script and qmd generation

**Comment by jzadra** [comment]
The following RSS feeds suggested above either do not have rss feeds, or link to empty xml documents:

## Local news sources (and RSS feeds)

### Santa Barbara

  * [Edhat | Local News From Your Community](https://www.edhat.com/) ([rss.xml](https://www.edhat.com/rss.xml))

### TODO: San Luis Obisbo (for Morro Bay)

## Priority feeds / example news items:

* [HA Foundation: News & Events | New Redwood CORE Hub Proposes Ambitious ‘Carbon N](https://www.hafoundation.org/About-Us/All-News/ArticleId/77/redwoodcore-announcement)
 * [CA Energy Commission: State Approves $10.5 Million to Prepare the Port of Humboldt Bay for Offshore Wind](https://www.energy.ca.gov/news/2022-03/state-approves-105-million-prepare-port-humboldt-bay-offshore-wind)

**Comment by jzadra** [comment]
The issue with the news item below is not clear.  It appears to break at the `$`, however there are 15 other news items that have `$` in the title and do not have an issue.

![image](https://user-images.githubusercontent.com/25590353/209887119-4e837257-1996-443e-96dd-ebdb7ce24668.png)

**Comment by jzadra** [comment]
It appears that this issue is due to it trying to render it as a mathjax equation.  I am still at a loss as to why. @bbest any ideas?

**Comment by jzadra** [comment]
Ok, I have further eliminated some possible causes - it turns out that the offending item "Landmark California"... is not the issue.  If it is removed, a different item has the same issue:
